name: Daily updates

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  updates:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - uses: flcdrg/rss-to-readme@v1.2.7
        with:
          feed-url: https://agdl.dev/feed.rss
          readme-section: feed
          empty-commits: false