name: Daily updates

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  updates:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://agdl.dev/feed.rss'
          file: 'README.md'
      - uses: sarisia/actions-commit@master